# Generated by Django 4.0.6 on 2022-07-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_deposit_withdrawal_delete_moneytransfer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
